# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_pan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(547, 483)
        self.lb_login = QtWidgets.QLabel(Form)
        self.lb_login.setGeometry(QtCore.QRect(220, 50, 120, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_login.setFont(font)
        self.lb_login.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_login.setObjectName("lb_login")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 120, 425, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_name.setFont(font)
        self.lb_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout_2.addWidget(self.lb_name)
        self.ed_name = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ed_name.setFont(font)
        self.ed_name.setStyleSheet("border-radius: 10px;\n"
"border: 2px groove white;")
        self.ed_name.setObjectName("ed_name")
        self.horizontalLayout_2.addWidget(self.ed_name)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 190, 425, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_pwd = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_pwd.setFont(font)
        self.lb_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pwd.setObjectName("lb_pwd")
        self.horizontalLayout_3.addWidget(self.lb_pwd)
        self.ed_pwd = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ed_pwd.setFont(font)
        self.ed_pwd.setStyleSheet("border-radius: 10px;\n"
"border: 2px groove white;")
        self.ed_pwd.setFrame(True)
        self.ed_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ed_pwd.setObjectName("ed_pwd")
        self.horizontalLayout_3.addWidget(self.ed_pwd)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 330, 431, 47))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_login = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet("    /*border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);\n"
"*/\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:white;\n"
"    background-color:rgb(79, 125, 163);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(127, 161, 190);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.btn_login.setAutoDefault(False)
        self.btn_login.setDefault(False)
        self.btn_login.setFlat(False)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout.addWidget(self.btn_login)
        self.btn_regist = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.btn_regist.setFont(font)
        self.btn_regist.setStyleSheet(
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:white;\n"
"    background-color:rgb(79, 125, 163);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(127, 161, 190);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.btn_regist.setObjectName("btn_regist")
        self.horizontalLayout.addWidget(self.btn_regist)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "登录注册"))
        self.lb_login.setText(_translate("Form", "用户登录"))
        self.lb_name.setText(_translate("Form", "账   号："))
        self.lb_pwd.setText(_translate("Form", "密   码："))
        self.btn_login.setText(_translate("Form", "登  录"))
        self.btn_regist.setText(_translate("Form", "注  册"))
