# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Regist_pane.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(547, 483)
        self.lb_regist = QtWidgets.QLabel(Form)
        self.lb_regist.setGeometry(QtCore.QRect(200, 20, 120, 24))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_regist.setFont(font)
        self.lb_regist.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_regist.setObjectName("lb_regist")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 330, 431, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_regist = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.btn_regist.setFont(font)
        self.btn_regist.setStyleSheet("    /*border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);\n"
"*/\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:white;\n"
"    background-color:rgb(79, 125, 163);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(127, 161, 190);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.btn_regist.setObjectName("btn_regist")
        self.horizontalLayout.addWidget(self.btn_regist)
        self.btn_exit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("    /*border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);\n"
"*/\n"
"QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:white;\n"
"    background-color:rgb(79, 125, 163);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(127, 161, 190);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}\n"
"\n"
"")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout.addWidget(self.btn_exit)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(50, 230, 421, 40))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_pwd_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_pwd_2.setFont(font)
        self.lb_pwd_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pwd_2.setObjectName("lb_pwd_2")
        self.horizontalLayout_2.addWidget(self.lb_pwd_2)
        self.ed_pwd_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ed_pwd_2.setFont(font)
        self.ed_pwd_2.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove white;\n"
"")
        self.ed_pwd_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ed_pwd_2.setObjectName("ed_pwd_2")
        self.horizontalLayout_2.addWidget(self.ed_pwd_2)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(50, 160, 425, 40))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_pwd = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_pwd.setFont(font)
        self.lb_pwd.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_pwd.setObjectName("lb_pwd")
        self.horizontalLayout_3.addWidget(self.lb_pwd)
        self.ed_pwd = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ed_pwd.setFont(font)
        self.ed_pwd.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove white;\n"
"")
        self.ed_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.ed_pwd.setObjectName("ed_pwd")
        self.horizontalLayout_3.addWidget(self.ed_pwd)
        self.layoutWidget3 = QtWidgets.QWidget(Form)
        self.layoutWidget3.setGeometry(QtCore.QRect(50, 90, 425, 40))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_name = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.lb_name.setFont(font)
        self.lb_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_name.setObjectName("lb_name")
        self.horizontalLayout_4.addWidget(self.lb_name)
        self.ed_name = QtWidgets.QLineEdit(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.ed_name.setFont(font)
        self.ed_name.setStyleSheet("border-radius: 10px;  \n"
"border: 2px groove white;\n"
"")
        self.ed_name.setObjectName("ed_name")
        self.horizontalLayout_4.addWidget(self.ed_name)

        self.retranslateUi(Form)
        self.btn_exit.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lb_regist.setText(_translate("Form", "用户注册"))
        self.btn_regist.setText(_translate("Form", "注  册"))
        self.btn_exit.setText(_translate("Form", "退  出"))
        self.lb_pwd_2.setText(_translate("Form", "确认密码："))
        self.lb_pwd.setText(_translate("Form", "密   码："))
        self.lb_name.setText(_translate("Form", "账   号："))
