# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(429, 315)
        Form.setStyleSheet("    /*background-color:rgb(220, 220, 220);")
        self.price = QtWidgets.QLabel(Form)
        self.price.setEnabled(True)
        self.price.setGeometry(QtCore.QRect(50, 60, 121, 24))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.priceArea_2 = QtWidgets.QTextEdit(Form)
        self.priceArea_2.setGeometry(QtCore.QRect(40, 100, 331, 61))
        self.priceArea_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 10pt \"宋体\";")
        self.priceArea_2.setObjectName("priceArea_2")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 230, 331, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.priceButton_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.priceButton_3.sizePolicy().hasHeightForWidth())
        self.priceButton_3.setSizePolicy(sizePolicy)
        self.priceButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.priceButton_3.setMaximumSize(QtCore.QSize(150, 40))
        self.priceButton_3.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);")
        self.priceButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/ind.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.priceButton_3.setIcon(icon)
        self.priceButton_3.setObjectName("priceButton_3")
        self.horizontalLayout.addWidget(self.priceButton_3)
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.priceButton_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.priceButton_2.sizePolicy().hasHeightForWidth())
        self.priceButton_2.setSizePolicy(sizePolicy)
        self.priceButton_2.setMaximumSize(QtCore.QSize(150, 40))
        self.priceButton_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);")
        self.priceButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/arc.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.priceButton_2.setIcon(icon1)
        self.priceButton_2.setObjectName("priceButton_2")
        self.horizontalLayout.addWidget(self.priceButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.price.setText(_translate("Form", "卡号"))
import ui.image_rc
