# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'useInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 531)
        Form.setStyleSheet("/*background-color:rgb(220, 220, 220);")
        self.priceButton_2 = QtWidgets.QPushButton(Form)
        self.priceButton_2.setGeometry(QtCore.QRect(560, 420, 191, 61))
        self.priceButton_2.setStyleSheet("QPushButton\n"
"{\n"
"    font-family:Microsoft Yahei;\n"
"    color:white;\n"
"    background-color:rgb(79, 125, 163);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color:rgb(127, 161, 190);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(14 , 135 , 228);\n"
"    padding-left:3px;\n"
"    padding-top:3px;\n"
"}")
        self.priceButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/quren.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.priceButton_2.setIcon(icon)
        self.priceButton_2.setObjectName("priceButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 22, 441, 491))
        self.label.setStyleSheet(" border-radius: 10px;  \n"
"     border: 2px groove white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(470, 30, 361, 281))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.price_2 = QtWidgets.QLabel(self.widget)
        self.price_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_2.setFont(font)
        self.price_2.setObjectName("price_2")
        self.horizontalLayout.addWidget(self.price_2)
        self.stu_id = QtWidgets.QTextEdit(self.widget)
        self.stu_id.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 17pt \"宋体\";")
        self.stu_id.setObjectName("stu_id")
        self.stu_id.setFocusPolicy(QtCore.Qt.NoFocus)   #禁止编辑
        self.horizontalLayout.addWidget(self.stu_id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.price_3 = QtWidgets.QLabel(self.widget)
        self.price_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_3.setFont(font)
        self.price_3.setObjectName("price_3")
        self.horizontalLayout_2.addWidget(self.price_3)
        self.stu_id_2 = QtWidgets.QTextEdit(self.widget)
        self.stu_id_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 17pt \"宋体\";")
        self.stu_id_2.setObjectName("stu_id_2")
        self.stu_id_2.setFocusPolicy(QtCore.Qt.NoFocus)   #禁止编辑
        self.horizontalLayout_2.addWidget(self.stu_id_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.price_8 = QtWidgets.QLabel(self.widget)
        self.price_8.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_8.setFont(font)
        self.price_8.setObjectName("price_8")
        self.horizontalLayout_7.addWidget(self.price_8)
        self.stu_id_7 = QtWidgets.QTextEdit(self.widget)
        self.stu_id_7.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 17pt \"宋体\";")
        self.stu_id_7.setObjectName("stu_id_7")
        self.stu_id_7.setFocusPolicy(QtCore.Qt.NoFocus)   #禁止编辑
        self.horizontalLayout_7.addWidget(self.stu_id_7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.price_4 = QtWidgets.QLabel(self.widget)
        self.price_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_4.setFont(font)
        self.price_4.setObjectName("price_4")
        self.horizontalLayout_3.addWidget(self.price_4)
        self.stu_id_3 = QtWidgets.QTextEdit(self.widget)
        self.stu_id_3.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 17pt \"宋体\";")
        self.stu_id_3.setObjectName("stu_id_3")
        self.stu_id_3.setFocusPolicy(QtCore.Qt.NoFocus)   #禁止编辑
        self.horizontalLayout_3.addWidget(self.stu_id_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.price_2.setText(_translate("Form", "学号"))
        self.price_3.setText(_translate("Form", "姓名"))
        self.price_8.setText(_translate("Form", "班级"))
        self.price_4.setText(_translate("Form", "是否本人"))
import ui.image_rc
