# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 531)
        Form.setStyleSheet("    /*background-color:rgb(220, 220, 220);")
        self.priceButton_2 = QtWidgets.QPushButton(Form)
        self.priceButton_2.setGeometry(QtCore.QRect(580, 330, 191, 61))
        self.priceButton_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    background-color:rgb(229, 229, 229);")
        self.priceButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/arc.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.priceButton_2.setIcon(icon)
        self.priceButton_2.setObjectName("priceButton_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 22, 441, 491))
        self.label.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(470, 30, 371, 201))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.price_2 = QtWidgets.QLabel(self.widget)
        self.price_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_2.setFont(font)
        self.price_2.setObjectName("price_2")
        self.horizontalLayout.addWidget(self.price_2)
        self.stu_id = QtWidgets.QTextEdit(self.widget)
        self.stu_id.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 10pt \"宋体\";")
        self.stu_id.setObjectName("stu_id")
        self.horizontalLayout.addWidget(self.stu_id)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.price_3 = QtWidgets.QLabel(self.widget)
        self.price_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_3.setFont(font)
        self.price_3.setObjectName("price_3")
        self.horizontalLayout_2.addWidget(self.price_3)
        self.stu_id_2 = QtWidgets.QTextEdit(self.widget)
        self.stu_id_2.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 10pt \"宋体\";")
        self.stu_id_2.setObjectName("stu_id_2")
        self.horizontalLayout_2.addWidget(self.stu_id_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(10, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.price_4 = QtWidgets.QLabel(self.widget)
        self.price_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.price_4.setFont(font)
        self.price_4.setObjectName("price_4")
        self.horizontalLayout_3.addWidget(self.price_4)
        self.stu_id_3 = QtWidgets.QTextEdit(self.widget)
        self.stu_id_3.setStyleSheet("    border-radius: 10px;  \n"
"     border: 2px groove white;\n"
"    font: 10pt \"宋体\";")
        self.stu_id_3.setObjectName("stu_id_3")
        self.horizontalLayout_3.addWidget(self.stu_id_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.price_2.setText(_translate("Form", "学号"))
        self.price_3.setText(_translate("Form", "姓名"))
        self.price_4.setText(_translate("Form", "班级"))
import ui.image_rc
